FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8081
EXPOSE 8080

ARG APP_UID=1000
USER $APP_UID

ARG BUILD_CONFIGURATION=Production
ENV ASPNETCORE_ENVIRONMENT=$BUILD_CONFIGURATION

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src


COPY ["minimalApi.csproj", "./"]
RUN dotnet restore "minimalApi.csproj"

COPY . .

RUN dotnet build "minimalApi.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
RUN dotnet publish "minimalApi.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app

COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "minimalApi.dll"]


